<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 character.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/assets/blog/blender/ character.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.PointLight
      intensity={54351.41}
      decay={2}
      position={[4.08, 5.9, -1.01]}
      rotation={[-1.84, 0.6, 1.93]}
    />
    <T.Mesh
      geometry={gltf.nodes.Head.geometry}
      material={gltf.materials['Material.001']}
      position={[0.07, 1.07, -0.02]}
      scale={0.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Torso.geometry}
      material={gltf.materials['Material.001']}
      position={[0.06, 0.6, 0]}
      scale={0.24}
    />
    <T.Mesh
      geometry={gltf.nodes.pelvis.geometry}
      material={gltf.materials['Material.001']}
      position={[0.07, 0.3, 0]}
      scale={0.14}
    />
    <T.Mesh
      geometry={gltf.nodes.arm.geometry}
      material={gltf.materials['Material.001']}
      position={[0.32, 0.73, -0.03]}
      scale={-0.08}
    />
    <T.Mesh
      geometry={gltf.nodes.hand.geometry}
      material={gltf.materials['Material.001']}
      position={[0.71, 0.28, -0.21]}
      rotation={[-0.32, 0, 0]}
      scale={0.08}
    />
    <T.Mesh
      geometry={gltf.nodes.leg.geometry}
      material={gltf.materials['Material.001']}
      position={[0.34, -0.09, -0.24]}
      scale={0.19}
    />
    <T.Mesh
      geometry={gltf.nodes.shoe.geometry}
      material={gltf.materials['Material.001']}
      position={[0.31, -0.83, -0.04]}
      scale={[0.05, 0.05, 0.14]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
