<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./donut.glb
-->
<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import { OrbitControls } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()
  ref = new Group()

  const gltf = useGltf('/assets/blog/blender/donut.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}  
  {:then gltf}
    <T.Group name="Scene">
      <T.PerspectiveCamera
        makeDefault
        position={[0.75, 0.75, 0.75]}
        oncreate={(ref) => {
          ref.lookAt(0, 0, 0)    
        }}
      >
        <OrbitControls enableZoom={false} />
      </T.PerspectiveCamera>
      <T.DirectionalLight intensity={2} position={[0, 10, 10]} />

      <T.Group
        name="reference"
        position={[0.26, -0.65, -0.01]}
        rotation={[1.51, 0, 0]}
        scale={0.6}
      />
      <T.Mesh
        name="Table"
        geometry={gltf.nodes.Table.geometry}
        material={gltf.materials['Material.003']}
        position={[-0.07, 0, 0]}
        scale={1.36}
      >
        <T.Mesh
          name="Cup"
          geometry={gltf.nodes.Cup.geometry}
          material={gltf.materials.Poliigon_CeramicPotteryGlazed_10828_2K}
          position={[0.35, 0.1, -0.01]}
          scale={[0.74, 1.2, 0.74]}
        >
          <T.Mesh
            name="Foam"
            geometry={gltf.nodes.Foam.geometry}
            material={gltf.materials.Poliigon_FoodCoffee_10827_2K}
          />
        </T.Mesh>
        <T.Mesh
          name="plate"
          geometry={gltf.nodes.plate.geometry}
          material={gltf.materials.Poliigon_CeramicPotteryGlazed_10861_2K}
          position={[0.09, 0, 0.33]}
          scale={0.81}
        >
          <T.Mesh
            name="Donut"
            geometry={gltf.nodes.Donut.geometry}
            material={gltf.materials.Poliigon_FoodPastryDonut_10737_2K}
            position={[0, 0.05, -0.02]}
            scale={0.91}
          >
            <T.Mesh
              name="Icing"
              geometry={gltf.nodes.Icing.geometry}
              material={gltf.materials.Poliigon_FoodGlazeStrawberry_10739_2K}
              position={[0, 0.03, 0]}
            />
          </T.Mesh>
        </T.Mesh>
      </T.Mesh>
      <T.Mesh
        name="Plane"
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.nodes.Plane.material}
        position={[-0.23, 0.93, -1.35]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.48}
      />
      <T.Mesh
        name="Plane001"
        geometry={gltf.nodes.Plane001.geometry}
        material={gltf.nodes.Plane001.material}
        position={[1.23, 0.46, 0.78]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={1.59}
      />
      <T.Mesh
        name="Sprinkle"
        geometry={gltf.nodes.Sprinkle.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.26, 0.13, 0.07]}
        scale={[1, 0.74, 1]}
      />
      <T.Mesh
        name="Sprinkle001"
        geometry={gltf.nodes.Sprinkle001.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.27, 0.13, 0.07]}
        scale={[1, 0.71, 1]}
      />
      <T.Mesh
        name="Sprinkle002"
        geometry={gltf.nodes.Sprinkle002.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.27, 0.13, 0.07]}
        scale={[1, 0.71, 1]}
      />
      <T.Mesh
        name="Sprinkle003"
        geometry={gltf.nodes.Sprinkle003.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.27, 0.13, 0.07]}
        scale={[1, 0.74, 1]}
      />
      <T.Mesh
        name="Sprinkle004"
        geometry={gltf.nodes.Sprinkle004.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.26, 0.13, 0.07]}
        scale={[1, 0.55, 1]}
      />
      <T.Mesh
        name="Sprinkle005"
        geometry={gltf.nodes.Sprinkle005.geometry}
        material={gltf.materials['Material.001']}
        position={[-0.28, 0.13, 0.07]}
        scale={[1, 0.53, 1]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
