<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 girl.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/assets/blog/blender/girl.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.PointLight
      intensity={54351.41}
      decay={2}
      position={[4.08, 5.9, -1.01]}
      rotation={[-1.84, 0.6, 1.93]}
    />
    <T.Mesh
      geometry={gltf.nodes.head.geometry}
      material={gltf.materials.Material}
      position={[0, 3.54, 0.01]}
      scale={0.49}
    />
    <T.Mesh
      geometry={gltf.nodes.legs.geometry}
      material={gltf.materials.Material}
      position={[0, 1.51, -0.23]}
      scale={[0.16, 0.49, 0.16]}
    />
    <T.Mesh
      geometry={gltf.nodes.ear.geometry}
      material={gltf.materials.Material}
      position={[0.05, 3.67, -0.41]}
      rotation={[-0.61, -0.02, -1.5]}
      scale={[0.14, 0.02, 0.14]}
    />
    <T.Mesh
      geometry={gltf.nodes.Hair_bun.geometry}
      material={gltf.materials.Material}
      position={[-0.35, 4.28, 0]}
      rotation={[0, 0, 0.54]}
      scale={0.36}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
